version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  activiti-cloud-sso-idm:
    image: activiti/activiti-cloud-sso-idm:7-201710-EA
    ports:
      - "8180:8180"
  activiti-cloud-registry:
    image: activiti/activiti-cloud-registry:7-201710-EA
    ports:
     - "8761:8761"
  activiti-cloud-gateway:
    image: activiti/activiti-cloud-gateway:7-201710-EA
    depends_on:
     - activiti-cloud-registry
    ports:
     - "8080:8080"
