version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  activiti-cloud-keycloak:
    image: activiti/activiti-cloud-keycloak:latest
    ports:
      - "8180:8180"
  activiti-cloud-audit:
    image: activiti/activiti-cloud-audit:latest
    links:
      - activiti-cloud-keycloak:activiti-keycloak
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
  activiti-cloud-registry:
    image: activiti/activiti-cloud-registry:latest
    ports:
     - "8761:8761"
  activiti-cloud-gateway:
    image: activiti/activiti-cloud-gateway:latest
    depends_on:
     - activiti-cloud-registry
    ports:
     - "8080:8080"
  activiti-cloud-runtime-bundle:
    image: activiti/activiti-cloud-runtime-bundle:latest
    links:
      - activiti-cloud-keycloak:activiti-cloud-keycloak
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    depends_on:
      - rb-postgres
    volumes:
      - ./processes/:/processes/
  rb-postgres:
      image: postgres
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=postgres
       - POSTGRES_DB=activitidb
  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"
