# Default values for activitiinfrachart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: salaboy/rb-my-app
  tag: latest
  pullPolicy: IfNotPresent
rb:
  name: rb-my-app
  port: 8081
  debug: false
  trace: false
infra:
  release:
    name: infrareleasename